server:
  port: 8083

spring:
  application:
    name: request-service

  datasource:
    url: jdbc:postgresql://localhost:5436/requests
    username: request_user
    password: request_pass

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
